---
test_name: test_replica_quorum_failure

percona_links:
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/percona.yaml
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/sql-test.sh

percona_files:
  - percona.yaml
  - sql-test.sh

replace_item:
  - demo-vol1-claim
  - demo-vol1

replace_with:
  - test-rep-failure
  - test-rep

interval: 3

namespace: replica-quorum

fault_injection_file: inject_replica_quorum_failure.yml

storage_class_file: replica-quorum-sc.yaml

test_pod_regex: maya*|openebs*|pvc*|percona*

test_log_path: setup/logs/replica_quorum_failure_test.log

test_suite_id: 826

test_case_id: 166359
