---
test_name: verify_replica_deployment_with_node_affinity

patch_file: replica_patch.yml

create_sc: storage-class.yaml

percona_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/percona/demo-percona-mysql-pvc.yaml

test_pod_regex: maya*|openebs*|pvc*|percona*|

test_log_path: setup/logs/node_affinity_test.log

namespace: replica-affinity

test_suite_id: 826

test_case_id: 166367
