---
platform: ubuntu

#########################################
# Kubernetes Deployment Specification   #
#########################################

#Kubernetes Version to be used for deployment
#Accepted Entries (Valid Kubernetes Version): default:1.6.3
#Accepted Entries (Valid Weave Version): default:1.9.4

k8s_version: 1.7.8 
weave_version: 2.0.4

#list of kubernetes versions released.
#do not tamper the list unless you know
#what you are doing...

k8s_version_list:
  - 1.7.5
  - 1.7.8

weave_version_list:
  - 1.9.4
  - 2.0.4 
#Option to specify OpenEBS deployment type
# It can be either kubectl or helm based installation

openebs_deploy: kubectl
#########################################
# OpenEBS Deployment Specifications     #
#########################################

#Mode of openEBS deployment 
#Accepted Entries (dedicated, hyperconverged): default:hyperconverged 

deployment_mode: hyperconverged 

#OpenEBS operator namespace
operator_ns: openebs

#Option specifically for vagrant VMs
#Accepted Entries(true, false): default:false

is_vagrant_vm: true

#########################################
# Ansible Runtime Specifications        #
#########################################

#Option to run the sample demo of OpenEBS
#Accepted Entries(true, false): default:true

run_demo: true

#Option to setup Ansible Runtime Analysis playbook recorder
#Accepted Entries(true, false): default:true

ara_setup: true 

#Option to enable slack notifications to specified channel
#Accepted Entries(true, false): default:true

slack_notify: true

#########################################
# OpenEBS Test Specifications           #
#########################################

#Option to run cleanup functions in tests
#Accepted Entries(true, false): default:true

clean: true

#Option to capture logs for test runs
#Accepted Entries(true, false): default:true
logging: true

#########################################
# OpenEBS CI Specifications             #
#########################################

#Option to select type of CI build
#Accepted Entries(quick, normal): default:normal
#quick build uses preconfigured VMs, 
#normal builds upon vanilla VMs
vagrant_path: openebs/k8s/vagrant/1.8.8/ubuntu/
utils_path: openebs/e2e/ansible/playbooks/utils
kubeconfig: .kube/config
build_type: normal

# In case , if you want to deploy openebs in the cluster in managed kubernetes services, specify "cluster_type= managed". By default specifying the cluster_type to local.
cluster_type: hosted

# This allows us to select the tool to create the disks based on the cloud the disks are being created on:
# Accepted Entries: GCP, AWS
cloud_provider: GCP

#Testrail Credentials
testrail_user: "{{ lookup('env','TESTRAIL_USER') }}"
testrail_password: "{{ lookup('env','TESTRAIL_PASS') }}"
