# This is an example YAML for upgrading cstor SPC. 
# Some of the values below needs to be changed to
# match your openebs installation. The fields are
# indicated with VERIFY
---
apiVersion: batch/v1
kind: Job
metadata:
  
  # VERIFY that you have provided a unique name for this upgrade job.
  # The name can be any valid K8s string for name. This example uses
  # the following convention: cstor-spc-<flattened-from-to-versions>-<spc-name>
  name: cstor-spc-100110-cstor-sparse-pool
  
  # VERIFY the value of namespace is same as the namespace where openebs components
  # are installed. You can verify using the command:
  # `kubectl get pods -n <openebs-namespace> -l openebs.io/component-name=maya-apiserver`
  # The above command should return status of the openebs-apiserver.
  namespace: openebs

spec:
  backoffLimit: 4
  template:
    spec:
      
      # VERIFY the value of serviceAccountName is pointing to service account
      # created within openebs namespace. Use the non-default account.
      # by running `kubectl get sa -n <openebs-namespace>`
      serviceAccountName: openebs-maya-operator

      containers:
      - name:  upgrade
        args:
        - "cstor-spc"
        - "--from-version=1.0.0"
        - "--to-version=1.1.0"
        
        # VERIFY that you have provided the correct SPC Name
        - "--spc-name=sparse-claim-auto"
        
        # Following are optional parameters
        # Log Level
        - "--v=4"
        
        # DO NOT CHANGE BELOW PARAMETERS
        env:
        - name: OPENEBS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        tty: true
        image: quay.io/openebs/m-upgrade:1.1.0
      restartPolicy: OnFailure
---
