---
- hosts: localhost

  vars_files:
    - snapshot-vars.yml

  tasks:
   - block:
       - include: simple-volume-prerequisites.yml

       - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/deploy_check.yml"
         vars:
            ns: "{{ operator_ns }}"
            app: maya-api

       - name: Store maya-apiserver pod name in variable
         set_fact:
           maya_pod: "{{ result.stdout.split()[0] }}"

       - name: Copy the volume claim to kube master
         copy:
           src: "{{ volume_def }}"
           dest: "{{ result_kube_home.stdout }}"
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

       - name: Create test specific namespace
         shell: source ~/.profile; kubectl create ns {{ namespace }}
         args:
           executable: /bin/bash
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

       - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/deploy_task.yml"
         vars:
           app_yml: "{{ volume_def }}"
           ns: "{{ namespace }}"

       - name: Confirm volume container is running
         shell: >
           source ~/.profile;
           kubectl get pods -n {{namespace}} | grep pvc | grep {{item}} | grep Running | wc -l
         args:
           executable: /bin/bash
         register: result
         until: result.stdout|int >= 1
         delay: 30
         retries: 10
         with_items:
           - ctrl
           - rep
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

       - name: Get storage ctrl pod name
         shell: source ~/.profile; kubectl get pods -n {{namespace}}  | grep ctrl
         args:
           executable: /bin/bash
         register: ctrl_name
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"

       - name: Set ctrl pod name to variable
         set_fact:
           ctrl_pod_name: "{{ ctrl_name.stdout.split()[0] }}"
           vol_name: "{{ ctrl_name.stdout.split()[0].split('-ctrl-')[0] }}"

       - name: Get IP address of ctrl pod
         shell: source ~/.profile; kubectl describe pod {{ ctrl_pod_name }} -n {{namespace}} | grep IP
         args:
           executable: /bin/bash
         register: ctrl_IP
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: Set IP of Pod to variable
         set_fact:
           ctrl_ip: "{{ ctrl_IP.stdout_lines[0].split()[1]}}"

       #- name: Establish iSCSI session with volume
       #  open_iscsi:
       #    show_nodes: yes
       #    portal: "{{ ctrl_ip }}"
       #    discover: true
       #    login: true
       #  register: result
       #  until: "'iqn' in result.nodes[0]"
       #  retries: 6
       #  delay: 10
       #  become: true
       #  delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Establish iSCSI session with volume
         shell: iscsiadm -m discovery -t st -p {{ ctrl_ip }}:3260
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"
         register: result

       - name: Store target iqn in variable
         set_fact:
           iqn: "{{result.stdout.split(',')[1].split()[1]}}"

       - name: Login to iSCSI target
         open_iscsi:
           show_nodes: yes
           login: yes
           target: "{{iqn}}"
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"
         register: result

       - name: Check device nodes
         set_fact:
           scsi_device: "{{result.devicenodes[0]}}"

       - name: Create file system on iSCSI disk
         filesystem:
           fstype: ext4
           dev: "{{scsi_device}}"
           force: no
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Mount device by Label
         mount:
           name: "{{mount_point}}"
           src: "{{scsi_device}}"
           fstype: ext4
           opts: discard,_netdev
           state: mounted
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Place test data into volume
         command: >
           dd if=/dev/urandom of={{mount_point}}/f1
           bs=512 count={{test_data_size | int * 1024}}
         args:
           creates: "{{mount_point}}/f1"
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Get the checksum of file created
         stat:
           path: "{{mount_point}}/f1"
           checksum_algorithm: "{{checksum}}"
         become: true
         register: result
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Save checksum to variable
         set_fact:
           ckey: "{{result.stat.checksum}}"
         failed_when: result.stat.checksum is not defined

       - name: Unmount the volume
         mount:
           name: "{{mount_point}}"
           state: unmounted
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Create volume snapshot
         shell: >
           source ~/.profile;
           kubectl exec {{maya_pod}} -n openebs -c maya-apiserver
           -- mayactl snapshot create --volname {{vol_name}} -n {{namespace}}
           --snapname {{snap_name}}
         args:
           executable: /bin/bash
         register: result_snap
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         failed_when: "'Created' not in result_snap.stdout"

       - name: Confirm successful snapshot creation
         shell: >
           source ~/.profile;
           kubectl exec {{maya_pod}} -n openebs -c maya-apiserver
           -- mayactl snapshot list --volname {{vol_name}} -n {{namespace}}
         args:
           executable: /bin/bash
         register: result_snap_list
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         failed_when: "snap_name not in result_snap_list.stdout"

       - name: Remount the volume
         mount:
           name: "{{mount_point}}"
           src: "{{scsi_device}}"
           fstype: ext4
           opts: discard,_netdev
           state: mounted
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Remove the file created
         file:
           path: "{{mount_point}}/f1"
           state: absent
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Unmount the volume again before snap revert
         mount:
           name: "{{mount_point}}"
           state: unmounted
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Revert volume snapshot
         shell: >
           source ~/.profile;
           kubectl exec {{maya_pod}} -n openebs -c maya-apiserver
           -- mayactl snapshot revert --volname {{vol_name}} -n {{namespace}}
           --snapname {{snap_name}}
         args:
           executable: /bin/bash
         register: result_snap
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         failed_when: "'Reverting to snapshot' not in result_snap.stdout"

       - name: Remount the volume
         mount:
           name: "{{mount_point}}"
           src: "{{scsi_device}}"
           fstype: ext4
           opts: discard,_netdev
           state: mounted
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Check if file is present
         stat:
           path: "{{mount_point}}/f1"
           checksum_algorithm: "{{checksum}}"
         become: true
         register: result
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"
         failed_when: result.stat.exists is not defined and result.stat.exists != True

       - name: Store checksum into variable
         set_fact:
           rkey: "{{result.stat.checksum}}"
         failed_when: result.stat.checksum is not defined

       - name: Compare the file checksum after revert
         debug:
           msg: "Verified snapshot create and revert successfully"
         failed_when: rkey != ckey

       - name: Unmount the storage volume as part of cleanup
         mount:
           name: "{{mount_point}}"
           state: unmounted
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Tear down iSCSI sessions
         open_iscsi:
           login: no
           target: "{{ iqn }}"
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Remove stale node entries for ISCSI target
         command: iscsiadm -m node -T {{iqn}} -o delete
         become: true
         delegate_to: "{{groups['kubernetes-kubeminions'].0}}"

       - name: Test Passed
         set_fact:
           flag: "Test Passed"
           status_id: 1

       - name: Set Status
         set_fact:
           status: "good"

     rescue:
       - name: Test Failed
         set_fact:
           flag: "Test Failed"
           status_id: 5

       - name: Set Status
         set_fact:
           status: "danger"

     always:
      - block:
        - include: snapshot-cleanup.yml


        - name: Test Cleanup Pass
          set_fact:
            cflag: "Cleanup Passed"

        rescue:
        - name: Test Cleanup Fail
          set_fact:
            cflag: "Cleanup Failed"

        always:
        - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/stern_task.yml"
          vars:
            status: stop

           - name: Update Testrail
             shell: source ~/.profile; python3 {{ inventory_dir | dirname }}/files/updater.py -tuser {{ testrail_user }} -tpass {{ testrail_password }} -sid {{ test_suite_id }} -cid {{ test_case_id }} -stid {{ status_id }}
             args:
               executable: /bin/bash

           - name: Testrail Updated
             set_fact:
               tflag: "Testrail Updated"

         rescue:
           - name: Testrail Update failed
             set_fact:
               tflag: "Testrail Update Failed"

        - name: Send slack notification
          slack:
            token: "{{ lookup('env','SLACK_TOKEN') }}"
            msg: '{{ ansible_date_time.time }} TEST: {{test_name}}, RESULT: {{ flag }}, {{ cflag }},{{tflag}}'
            color: "{{status}}"
          when: slack_notify | bool and lookup('env','SLACK_TOKEN')

