---
test_name: test_nw_failure_ctrl

percona_links:
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/percona.yaml
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/sql-test.sh

percona_files:
  - percona.yaml
  - sql-test.sh

replace_item:
  - demo-vol1-claim
  - demo-vol1

replace_with:
  - test-nw-failure
  - test-nw

namespace: nw-ctrl

delay_interavals: 
  - 3000
  - 6000
  - 10000

pumba_file: pumba_kube.yml 

test_pod_regex: maya*|openebs*|pvc*|percona*|pumba*

test_log_path: setup/logs/network_failure_test.log

test_suite_id: 826

test_case_id: 166360
