---
test_name: ha_pod_reschedule

test_log_path: setup/logs/ha_pod_reschedule.log

test_pod_regex: maya*|openebs*|pvc*|percona*

percona_mysql_plugin_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/percona/demo-percona-mysql-pvc.yaml

pod_yaml_alias: demo-percona-mysql-pvc.yaml

deb_packages:
  - mysql-client
             
namespace: ha-name

utils_path: openebs/e2e/ansible/playbooks/utils 

test_suite_id: 826

test_case_id: 166355
