---
test_name: test_ctrl_failure

percona_links:
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/percona.yaml
  - https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/sql-test.sh

percona_files:
  - percona.yaml
  - sql-test.sh

chaoskube_files:
  - rbac.yaml
  - chaoskube.yaml

replace_item:
  - demo-vol1-claim
  - demo-vol1

replace_with:
  - test-ctrl-failure
  - test-ctrl

namespace: ctrl-failure

chaos_duration: 120

chaos_interval: 20

test_pod_regex: maya*|openebs*|pvc*|percona*|chaos*

test_log_path: setup/logs/controller_failure_test.log

test_suite_id: 826

test_case_id: 166357
